before_script:
  - python setup.py install

test:2.7:
  image: python:2.7-alpine
  type: test
  script:
    - python setup.py test

test:3.3:
  image: python:3.3-alpine
  type: test
  script:
    - python setup.py test

test:3.4:
  image: python:3.4-alpine
  type: test
  script:
    - python setup.py test

test:3.5:
  image: python:3.5-alpine
  type: test
  script:
    - python setup.py test

test:3.6:
  image: python:3.6-alpine
  type: test
  script:
    - python setup.py test
