language: python
python:
    - "2.5"
    - "2.6"
    - "2.7"
    - "3.2"
    - "pypy"
install:
    - if [ "$TRAVIS_PYTHON_VERSION" == "2.5" ]; then pip --quiet install unittest2; fi
    - if [ "$TRAVIS_PYTHON_VERSION" == "2.6" ]; then pip --quiet install unittest2; fi
    - python setup.py install
script:
    - python setup.py test
