language: python
python:
    - "2.5"
    - "2.6"
    - "2.7"
    - "3.2"
install:
    - pip install --use-mirrors -r tests/travis/requirements-${TRAVIS_PYTHON_VERSION}.txt
    - python setup.py install
script:
    - python setup.py test
